# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "clients.baml": "// Present ONLY to satisfy ExtractDynamic's required `client` field. BAML is used\n// parser-only here (b.parse.*), so this client is NEVER actually invoked — no\n// LLM call is ever made from swe_af. The CLI harness providers own every model\n// call. env.ANTHROPIC_API_KEY need not even be set for the parse path.\nclient<llm> AnthropicClient {\n  provider anthropic\n  options {\n    model \"claude-3-5-sonnet-20241022\"\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n",
    "functions.baml": "// The load-bearing dynamic pieces. DynamicOutput has NO static fields; its shape\n// is supplied at call time via TypeBuilder (swe_af/baml_bridge.pydantic_to_typebuilder),\n// letting one BAML function parse any runtime SWE-AF schema.\nclass DynamicOutput {\n  @@dynamic\n}\n\nfunction ExtractDynamic(prompt: string) -> DynamicOutput {\n  client AnthropicClient\n  prompt #\"\n    {{ prompt }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
    "generators.baml": "// Generates the Python (pydantic) baml_client used by swe_af/baml_bridge.py.\n// version MUST equal the installed baml-py (see pyproject.toml).\ngenerator target {\n    output_type \"python/pydantic\"\n    output_dir \"../\"\n    version \"0.222.0\"\n    default_client_mode sync\n}\n",
}

def get_baml_files():
    return _file_map